name: unit/build tests

on: [push, pull_request]

jobs:
  # job name
  build_and_unit_test:

    # Run on Ubuntu
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    name: Build and run unit tests

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: build tests
        run: |
          A2D_ROOT=$(pwd);

          git clone https://github.com/kokkos/kokkos.git extern/kokkos;
          cd extern/kokkos;
          git checkout tags/3.6.01;
          mkdir build;
          cd build;
          cmake .. -DCMAKE_INSTALL_PREFIX=../../../installs/kokkos -G Ninja;
          ninja install;

          METIS_SOURCE_DIR=${A2D_ROOT}/extern;
          METIS_INSTALL_DIR=${A2D_ROOT}/installs/metis;
          cd $METIS_SOURCE_DIR;
          wget https://src.fedoraproject.org/lookaside/pkgs/metis/metis-5.1.0.tar.gz/5465e67079419a69e0116de24fce58fe/metis-5.1.0.tar.gz;
          tar -zxvf metis-5.1.0.tar.gz;
          cd metis-5.1.0;
          make config prefix=$METIS_INSTALL_DIR;
          make;
          make install;

          mkdir ${A2D_ROOT}/build;
          cd ${A2D_ROOT}/build;
          cmake .. -DCMAKE_BUILD_TYPE=Release -DA2D_BUILD_EXAMPLES=OFF -DA2D_BUILD_UNIT_TESTS=ON -G Ninja;
          ninja;

      - name: run unit tests
        run: |
          cd build/tests;
          ctest;
